stages:
  - build
  - package

.setup-mvn: &setup-mvn
  - chmod a+x mvnw

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - "**/target/"


build:
  stage: build
  image: ${CI_REGISTRY}/bi-ido/bi-ido-registry/maven:3.8.6-openjdk-18
  script:
    - *setup-mvn
    - ./mvnw package -DskipTests
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target/*.jar"

package:
  stage: package
  image: $CI_REGISTRY/ict/images/buildah:latest
  variables:
    BUILDAH_ISOLATION: chroot
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache ca-certificates curl buildah fuse-overlayfs netavark
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah info
  script:
    - buildah build --tag $IMAGE_TAG -f Dockerfile
    - buildah push --retry 3 $IMAGE_TAG