---
- name: Docker setup
  hosts: webservers
  tasks:
    - name: Install docker
      apk:
        name: docker
        state: present
    - name: Install docker py
      apk:
        name: docker-py
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: true
    - name: Login to docker
      community.docker.docker_login:
        registry_url: gitlab.fit.cvut.cz:5050
        username: gitlab+deploy-token-2618
        password: gldt-XYCNkwmyKsgoZgcLqDVc
    - name: Pull docker image
      community.docker.docker_image:
        name: "gitlab.fit.cvut.cz:5050/cernyj90/exam2"
        tag: "main"
        source: pull
    - name: Start docker container
      community.docker.docker_container:
        name: flightlog
        image: gitlab.fit.cvut.cz:5050/cernyj90/exam2:main
        recreate: true
        ports:
          - "80:8081"
